language: rust
cache: cargo
os: linux

git:
  depth: 1

env:
  - ARCH=x86_64
  - ARCH=i686

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
script:
  - cargo build --verbose
  - cargo test --verbose
