[package]
name = "gm8decompiler"
version = "2.0.0"
authors = ["GM8Emulator <gm8emulator@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = { version = "1.0.12", features = ["zlib"] }
getopts = "0.2.21"
gm8x = { path = "gm8x" }
minio  = { git = "https://github.com/notviri/minio" }
rayon = "1.2"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace]
members = ["gm8x"]
