[package]
name = "gm8decompiler"
version = "2.0.0"
authors = ["GM8Emulator <gm8emulator@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = { version = "1.0.12", features = ["zlib"] }
getopts = "0.2.21"
gm8x = { git = "https://github.com/OpenGM8/GM8Emulator" }
minio  = { git = "https://github.com/notviri/minio" }